"""GitHub API client for creating PRs."""

from github import Github
from github.GithubException import GithubException
from typing import Dict, Optional
import datetime
import re
import time


class GitHubClient:
    """Client for GitHub API operations."""
    
    def __init__(self, token: str, repo: str, base_branch: str = "main"):
        """Initialize GitHub client."""
        self.github = Github(token)
        self.repo_name = repo
        self.base_branch = base_branch
        self.repo = self.github.get_repo(repo)
    
    def is_repo_empty(self) -> bool:
        """Check if the repository is empty."""
        try:
            # Try to get the base branch reference
            self.repo.get_git_ref(f"heads/{self.base_branch}")
            return False  # Branch exists, repo is not empty
        except GithubException as e:
            if e.status == 409:  # Repository is empty
                return True
            # For other errors, try checking commits
            try:
                commits = list(self.repo.get_commits())
                return len(commits) == 0
            except GithubException:
                # If we can't check commits, assume empty to be safe
                return True
    
    def create_initial_commit(self) -> bool:
        """Create an initial commit if repository is empty."""
        try:
            # Create a README as initial commit
            self.repo.create_file(
                path="README.md",
                message="Initial commit",
                content="# ETL Pipelines\n\nThis repository contains ETL pipelines generated by the ETL Agent.\n",
                branch=self.base_branch
            )
            return True
        except GithubException as e:
            # If file already exists or other error, that's okay
            return True
    
    def create_branch(self, branch_name: str) -> bool:
        """Create a new branch from base branch."""
        try:
            # Check if repo is empty and create initial commit if needed
            if self.is_repo_empty():
                if not self.create_initial_commit():
                    return False
                # After initial commit, we can create branch from it
                # For empty repos, we'll create the branch directly with files
            
            try:
                base_ref = self.repo.get_git_ref(f"heads/{self.base_branch}")
                sha = base_ref.object.sha
                self.repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=sha)
                return True
            except GithubException as e:
                if e.status == 409:  # Repository still empty or branch doesn't exist
                    # Create branch by creating first file in it
                    # This will be handled by create_file
                    return True
                if e.status == 422:  # Branch already exists
                    return True
                raise
        except GithubException as e:
            if e.status == 422:  # Branch already exists
                return True
            if e.status == 409:  # Repository empty - will handle in create_file
                return True
            raise
    
    def create_file(self, branch: str, file_path: str, content: str, message: str) -> bool:
        """Create or update a file in the repository."""
        try:
            try:
                # Try to get existing file
                file = self.repo.get_contents(file_path, ref=branch)
                # Update existing file
                self.repo.update_file(
                    path=file_path,
                    message=message,
                    content=content,
                    sha=file.sha,
                    branch=branch
                )
            except GithubException:
                # File doesn't exist, create it
                self.repo.create_file(
                    path=file_path,
                    message=message,
                    content=content,
                    branch=branch
                )
            return True
        except GithubException as e:
            print(f"Error creating file: {e}")
            return False
    
    def create_pull_request(
        self,
        title: str,
        body: str,
        head_branch: str,
        base_branch: Optional[str] = None
    ) -> Optional[str]:
        """Create a pull request."""
        try:
            base = base_branch or self.base_branch
            pr = self.repo.create_pull(
                title=title,
                body=body,
                head=head_branch,
                base=base
            )
            return pr.html_url
        except GithubException as e:
            print(f"Error creating PR: {e}")
            return None
    
    def create_pr_with_files(
        self,
        files: Dict[str, str],
        pr_title: str,
        pr_body: str,
        branch_name: Optional[str] = None
    ) -> Optional[str]:
        """Create a PR with multiple files."""
        # Generate branch name if not provided
        if not branch_name:
            timestamp = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
            sanitized_title = re.sub(r'[^a-zA-Z0-9-]', '-', pr_title.lower())
            branch_name = f"etl-agent/{sanitized_title[:30]}-{timestamp}"
        
        # Check if repo is empty and handle it
        is_empty = self.is_repo_empty()
        
        if is_empty:
            # For empty repos, create initial commit on base branch first
            if not self.create_initial_commit():
                return None
            # Wait a moment for GitHub to process the initial commit
            time.sleep(2)  # Give GitHub time to process
        
        # Now create branch from base (should work now that base exists)
        if not self.create_branch(branch_name):
            return None
        
        # Create/update files on the branch
        for file_path, content in files.items():
            message = f"Add {file_path} via ETL Agent"
            if not self.create_file(branch_name, file_path, content, message):
                return None
        
        # Create PR
        return self.create_pull_request(pr_title, pr_body, branch_name)
